### ISSUE TITLE
No secondary info

### ISSUE THREAD

**Issue by PierreScerri** [benct/lovelace-battery-entity-row#12]
Hi

I have the following configuration.

```
type: 'custom:auto-entities'
card:
  type: entities
  title: Windows
filter:
  include:
    - entity_id: binary_sensor.*_window
      options:
        type: 'custom:battery-entity-row'
        warning: 85
        critical: 83
        secondary_info: last_updated
sort:
  method: attribute
  attribute: battery_level
```
The card displays this:
![Screenshot 2021-01-23 at 11 36 04](https://user-images.githubusercontent.com/34303331/105575901-57292780-5d6f-11eb-972e-b02177f43484.png)

Each entity has these attributes:
![Screenshot 2021-01-23 at 11 36 42](https://user-images.githubusercontent.com/34303331/105575907-690aca80-5d6f-11eb-8e6c-1b0100e4f9a0.png)

How can I get the display like this:
![Screenshot 2021-01-23 at 11 39 22](https://user-images.githubusercontent.com/34303331/105575959-d1f24280-5d6f-11eb-9a97-6c468f3c283d.png)

Thank you.

**Comment by benct** [comment]
Sorry for the late reply. It should be `last-updated`, not `last_updated`.

**Comment by PierreScerri** [comment]
Do you mean like this?
![Screenshot 2021-03-12 at 14 47 30](https://user-images.githubusercontent.com/34303331/110948656-eb604580-8341-11eb-99f9-01ec17238a9a.png)

Not working.

**Comment by benct** [comment]
Oh, my bad, `last-updated` isn't supported in the current version. However, I've just merged #10 which should fix this. Try upgrading when I get a new version out (soon).

**Comment by PierreScerri** [comment]
Super.  Thanks

**Comment by PierreScerri** [comment]
I updated to v1.3.0 and it is still not working.  Do I need to change anything in my config?

**Comment by PierreScerri** [comment]
BTW, last- changed shows nothing, last-updated shows 'never'
![Screenshot 2021-03-12 at 17 00 42](https://user-images.githubusercontent.com/34303331/110965534-8f52ec80-8354-11eb-8782-6084153c118a.png)

**Comment by benct** [comment]
Made a small mistake in `1.3.0`.. Should be fixed in `1.3.1` :)

**Comment by boardyuk** [comment]
> 
> 
> Made a small mistake in `1.3.0`.. Should be fixed in `1.3.1` :)

I've upgraded to 1.3.1 and am still getting 'Never' shown for both last-changed and last-updated.

**Comment by benct** [comment]
Remember to reload resources and hard-refresh the browser (or clear browser cache).

**Comment by PierreScerri** [comment]
Sorted.  Great job. Thanks.
![Screenshot 2021-03-12 at 17 24 56](https://user-images.githubusercontent.com/34303331/110968526-edcd9a00-8357-11eb-9f59-bfd2575c0249.png)

**Comment by Kurisutian** [comment]
I still have the browser show "Never" as the secondary info. I refreshed the browser, cleaning the cache but nothing shows up. Just checked and have v1.3.1 installed.
